version: '3.8'

services:
    web:
        image: homqyy/hengine:1.0
        ports:
            - "8000:80/tcp"
        restart: always
        volumes:
            - ./web/conf/nginx.conf:/usr/local/hengine/conf/nginx.conf:ro
            - ./mkdocs/site:/usr/local/hengine/html/site:ro

    mkdocs:
        image: homqyy/mkdocs
        build:
            context: ./mkdocs
        network_mode: host
        volumes:
            - ./mkdocs/project:/site
            - ./mkdocs/site:/site/site